apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  selector:  
    matchLabels:
      run: apache
  replicas: 1 
  template:   
    metadata:
      labels:
        run: apache
    spec:
      containers:
      - name: apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
              cpu: 500m
          requests:
              cpu: 200m
