apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: web
    name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      name: mongo-express
  template:
    metadata:
      labels:
         app: web
         name: mongo-express
    spec:
       containers:
       - name: mongo-express
         image: mongo-express
         env:
         - name: ME_CONFIG_MONGODB_SERVER
           value: mongo-0.mongodb-svc
         ports:
           - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
spec:
  type: LoadBalancer
  selector:
    app: web
    name: mongo-express
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081