apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: binding-sa
   namespace: default
subjects:
- kind: ServiceAccount
  name: sa1 
roleRef:
  kind: Role 
  name: sa-role
  apiGroup: rbac.authorization.k8s.io
