apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment  # Nombre del deployment
  namespace: nginx1-dev  # Namespace en el que se crea el deployment
  labels:
    app: nginx-manager  # Etiqueta para identificar la aplicación
spec:
  replicas: 1  # Número de réplicas del pod
  strategy:
    type: RollingUpdate  # Tipo de estrategia de despliegue
    rollingUpdate:
      maxSurge: 1  # Número máximo de pods que se pueden crear por encima del número deseado de pods
      maxUnavailable: 1  # Número máximo de pods que pueden estar no disponibles durante el proceso de actualización
  minReadySeconds: 2  # Número mínimo de segundos que un nuevo pod debe estar listo antes de ser considerado disponible
  selector:
    matchLabels:
      app: nginx-manager  # Selector de etiquetas para identificar los pods gestionados por este deployment
  template:
    metadata:
      labels:
        app: nginx-manager  # Etiqueta para identificar los pods
    spec:
      containers:
        - name: nginx1-manager  # Nombre del contenedor
          image: jc21/nginx-proxy-manager:v3  # Imagen Docker para el contenedor
          resources:
            limits:
              memory: "128Mi"  # Cantidad máxima de memoria que puede usar el contenedor
              cpu: "200m"  # Cantidad máxima de CPU que puede usar el contenedor
            requests:
              memory: "64Mi"  # Cantidad mínima de memoria garantizada para el contenedor
              cpu: "100m"  # Cantidad mínima de CPU garantizada para el contenedor
          ports:
            - containerPort: 80  # Puerto expuesto por el contenedor para tráfico HTTP
            - containerPort: 81  # Puerto expuesto por el contenedor para tráfico de redirección HTTP
            - containerPort: 443  # Puerto expuesto por el contenedor para tráfico HTTPS
          volumeMounts:
            - name: data-volume  # Nombre del volumen a montar
              mountPath: /data  # Ruta donde se monta el volumen en el contenedor
            - name: letsencrypt-volume  # Nombre del volumen a montar
              mountPath: /etc/letsencrypt  # Ruta donde se monta el volumen en el contenedor
      volumes:
        - name: data-volume  # Nombre del volumen
          hostPath:
            path: /path/to/data  # Ruta en el host para montar como volumen
        - name: letsencrypt-volume  # Nombre del volumen
          hostPath:
            path: /path/to/letsencrypt  # Ruta en el host para montar como volumen
