apiVersion: v1
kind: LimitRange
metadata:
  name: nginx-limit-range
  namespace: nginx1-dev
spec:
  limits:
    - type: Pod
      max:
        memory: 256Mi
        cpu: 200m
      min:
        memory: 128Mi
        cpu: 100m
