apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx1-dev
  labels:
    app: nginx-manager
spec:
  selector:
    app: nginx-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 81
      targetPort: 81
      name: http-redirect
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: LoadBalancer
